// <auto-generated />
using System;
using FlightBookingSystem.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightBookingSystem.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260714122420_MakeTicketNumberOptionalBeforePayment")]
    partial class MakeTicketNumberOptionalBeforePayment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FlightBookingSystem.Web.Models.ChangDatCho", b =>
                {
                    b.Property<int>("MaChangDatCho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoaiChang")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaChuyenBay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaPhieuDatCho")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThuTuChang")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaChangDatCho");

                    b.HasIndex("MaChuyenBay", "LoaiChang");

                    b.HasIndex("MaPhieuDatCho", "ThuTuChang")
                        .IsUnique();

                    b.ToTable("ChangDatChos");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.ChiTietDichVu", b =>
                {
                    b.Property<int>("MaChiTietDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Gia")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaHanhKhach")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaPhieuDatCho")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaVe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaChiTietDichVu");

                    b.HasIndex("MaDichVu");

                    b.HasIndex("MaHanhKhach")
                        .HasDatabaseName("IX_ChiTietDichVu_HanhKhach");

                    b.HasIndex("MaVe");

                    b.HasIndex("MaPhieuDatCho", "MaVe", "MaDichVu");

                    b.ToTable("ChiTietDichVus");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.ChuyenBay", b =>
                {
                    b.Property<int>("MaChuyenBay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CuaLen")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GiaCoBan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GioBatDauCheckIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GioHaCanh")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GioHaCanhThucTe")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GioKetThucCheckIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GioKhoiHanh")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GioKhoiHanhThucTe")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GioLenMayBay")
                        .HasColumnType("TEXT");

                    b.Property<string>("LyDoTreChuyen")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaLoTrinh")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaMayBay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NhaGa")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoHieuChuyenBay")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("MaChuyenBay");

                    b.HasIndex("MaMayBay");

                    b.HasIndex("MaLoTrinh", "GioKhoiHanh")
                        .HasDatabaseName("IX_ChuyenBay_TimKiem");

                    b.HasIndex("SoHieuChuyenBay", "GioKhoiHanh")
                        .IsUnique();

                    b.ToTable("ChuyenBays");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.DichVuThem", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Gia")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KhoiLuongKg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoaiDichVu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("MaDichVu");

                    b.HasIndex("LoaiDichVu", "TrangThai");

                    b.ToTable("DichVuThems");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.GheChuyenBay", b =>
                {
                    b.Property<int>("MaGheChuyenBay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GiaGhe")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GiuBoiTaiKhoanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GiuDenLuc")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaChuyenBay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaGheMayBay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaPhieuDatChoDangGiu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhienBan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThaiGhe")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("MaGheChuyenBay");

                    b.HasIndex("GiuBoiTaiKhoanId");

                    b.HasIndex("MaGheMayBay");

                    b.HasIndex("MaPhieuDatChoDangGiu");

                    b.HasIndex("MaChuyenBay", "MaGheMayBay")
                        .IsUnique();

                    b.HasIndex("MaChuyenBay", "TrangThaiGhe")
                        .HasDatabaseName("IX_GheChuyenBay_ChuyenBay");

                    b.HasIndex("MaChuyenBay", "TrangThaiGhe", "GiuDenLuc")
                        .HasDatabaseName("IX_GheChuyenBay_Realtime");

                    b.ToTable("GheChuyenBays");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.GheMayBay", b =>
                {
                    b.Property<int>("MaGheMayBay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DangSuDung")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaHangGhe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaMayBay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoGhe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("MaGheMayBay");

                    b.HasIndex("MaHangGhe");

                    b.HasIndex("MaMayBay", "SoGhe")
                        .IsUnique();

                    b.ToTable("GheMayBays");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.HangBay", b =>
                {
                    b.Property<int>("MaHangBay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuocGia")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenHangBay")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("MaHangBay");

                    b.HasIndex("MaCode")
                        .IsUnique();

                    b.ToTable("HangBays");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.HangGhe", b =>
                {
                    b.Property<int>("MaHangGhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HeSoGia")
                        .HasColumnType("TEXT");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenHangGhe")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("MaHangGhe");

                    b.HasIndex("TenHangGhe")
                        .IsUnique();

                    b.ToTable("HangGhes");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.HanhKhach", b =>
                {
                    b.Property<int>("MaHanhKhach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("LoaiGiayTo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("LoaiHanhKhach")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaPhieuDatCho")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NgayHetHanGiayTo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuocTich")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoGiayTo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("MaHanhKhach");

                    b.HasIndex("MaPhieuDatCho", "SoGiayTo");

                    b.ToTable("HanhKhachs");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.HoanTien", b =>
                {
                    b.Property<int>("MaHoanTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LyDo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaGiaoDichHoanTien")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaPhieuDatCho")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaThanhToan")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NgayHoanTien")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoTienHoan")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("MaHoanTien");

                    b.HasIndex("MaGiaoDichHoanTien")
                        .IsUnique()
                        .HasFilter("MaGiaoDichHoanTien IS NOT NULL");

                    b.HasIndex("MaPhieuDatCho");

                    b.HasIndex("MaThanhToan");

                    b.ToTable("HoanTiens");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.LoTrinh", b =>
                {
                    b.Property<int>("MaLoTrinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GiaCoBan")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KhoangCachKm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoaiDuongBay")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaSanBayDen")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaSanBayDi")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("MaLoTrinh");

                    b.HasIndex("MaSanBayDen");

                    b.HasIndex("MaSanBayDi", "MaSanBayDen")
                        .IsUnique()
                        .HasDatabaseName("IX_LoTrinh_TimKiem");

                    b.ToTable("LoTrinhs");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.MayBay", b =>
                {
                    b.Property<int>("MaMayBay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DongMayBay")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaHangBay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoHieuDangKy")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("TongSoGhe")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("MaMayBay");

                    b.HasIndex("MaHangBay");

                    b.HasIndex("SoHieuDangKy")
                        .IsUnique();

                    b.ToTable("MayBays");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.PhieuDatCho", b =>
                {
                    b.Property<int>("MaPhieuDatCho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailLienHe")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GiuDenLuc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTenLienHe")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("LoaiChuyenDi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaDatCho")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoaiLienHe")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("SoLuongHanhKhach")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("MaPhieuDatCho");

                    b.HasIndex("MaDatCho")
                        .IsUnique();

                    b.HasIndex("MaTaiKhoan")
                        .HasDatabaseName("IX_PhieuDatCho_TaiKhoan");

                    b.HasIndex("TrangThai", "GiuDenLuc")
                        .HasDatabaseName("IX_PhieuDatCho_HetHan");

                    b.ToTable("PhieuDatChos");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.SanBay", b =>
                {
                    b.Property<string>("MaSanBay")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuocGia")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSanBay")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThanhPho")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("MaSanBay");

                    b.ToTable("SanBays");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SoDienThoai")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("LyDoLoi")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaPhieuDatCho")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("TEXT");

                    b.Property<string>("NhaCungCap")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("IdempotencyKey IS NOT NULL");

                    b.HasIndex("MaGiaoDich")
                        .IsUnique()
                        .HasFilter("MaGiaoDich IS NOT NULL");

                    b.HasIndex("MaPhieuDatCho")
                        .HasDatabaseName("IX_ThanhToan_PhieuDatCho");

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.Ve", b =>
                {
                    b.Property<int>("MaVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GiaVe")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaChangDatCho")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaGheChuyenBay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaHanhKhach")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaPhieuDatCho")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayXuatVe")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoVeDienTu")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThaiVe")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("MaVe");

                    b.HasIndex("MaGheChuyenBay")
                        .IsUnique()
                        .HasDatabaseName("UQ_Ve_GheChuyenBay_ConHieuLuc")
                        .HasFilter("TrangThaiVe NOT IN ('Canceled', 'Refunded')");

                    b.HasIndex("MaHanhKhach");

                    b.HasIndex("MaPhieuDatCho")
                        .HasDatabaseName("IX_Ve_PhieuDatCho");

                    b.HasIndex("SoVeDienTu")
                        .IsUnique()
                        .HasFilter("SoVeDienTu IS NOT NULL");

                    b.HasIndex("MaChangDatCho", "MaHanhKhach")
                        .IsUnique();

                    b.ToTable("Ves");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.ChangDatCho", b =>
                {
                    b.HasOne("FlightBookingSystem.Web.Models.ChuyenBay", "ChuyenBay")
                        .WithMany("ChangDatChos")
                        .HasForeignKey("MaChuyenBay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem.Web.Models.PhieuDatCho", "PhieuDatCho")
                        .WithMany("ChangDatChos")
                        .HasForeignKey("MaPhieuDatCho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenBay");

                    b.Navigation("PhieuDatCho");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.ChiTietDichVu", b =>
                {
                    b.HasOne("FlightBookingSystem.Web.Models.DichVuThem", "DichVuThem")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem.Web.Models.HanhKhach", "HanhKhach")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("MaHanhKhach")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlightBookingSystem.Web.Models.PhieuDatCho", "PhieuDatCho")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("MaPhieuDatCho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem.Web.Models.Ve", "Ve")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("MaVe")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DichVuThem");

                    b.Navigation("HanhKhach");

                    b.Navigation("PhieuDatCho");

                    b.Navigation("Ve");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.ChuyenBay", b =>
                {
                    b.HasOne("FlightBookingSystem.Web.Models.LoTrinh", "LoTrinh")
                        .WithMany("ChuyenBays")
                        .HasForeignKey("MaLoTrinh")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem.Web.Models.MayBay", "MayBay")
                        .WithMany("ChuyenBays")
                        .HasForeignKey("MaMayBay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoTrinh");

                    b.Navigation("MayBay");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.GheChuyenBay", b =>
                {
                    b.HasOne("FlightBookingSystem.Web.Models.TaiKhoan", "GiuBoiTaiKhoan")
                        .WithMany("GheDangGius")
                        .HasForeignKey("GiuBoiTaiKhoanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FlightBookingSystem.Web.Models.ChuyenBay", "ChuyenBay")
                        .WithMany("GheChuyenBays")
                        .HasForeignKey("MaChuyenBay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem.Web.Models.GheMayBay", "GheMayBay")
                        .WithMany("GheChuyenBays")
                        .HasForeignKey("MaGheMayBay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem.Web.Models.PhieuDatCho", "PhieuDatChoDangGiu")
                        .WithMany("GheDangGius")
                        .HasForeignKey("MaPhieuDatChoDangGiu")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChuyenBay");

                    b.Navigation("GheMayBay");

                    b.Navigation("GiuBoiTaiKhoan");

                    b.Navigation("PhieuDatChoDangGiu");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.GheMayBay", b =>
                {
                    b.HasOne("FlightBookingSystem.Web.Models.HangGhe", "HangGhe")
                        .WithMany("GheMayBays")
                        .HasForeignKey("MaHangGhe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem.Web.Models.MayBay", "MayBay")
                        .WithMany("GheMayBays")
                        .HasForeignKey("MaMayBay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HangGhe");

                    b.Navigation("MayBay");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.HanhKhach", b =>
                {
                    b.HasOne("FlightBookingSystem.Web.Models.PhieuDatCho", "PhieuDatCho")
                        .WithMany("HanhKhachs")
                        .HasForeignKey("MaPhieuDatCho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuDatCho");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.HoanTien", b =>
                {
                    b.HasOne("FlightBookingSystem.Web.Models.PhieuDatCho", "PhieuDatCho")
                        .WithMany("HoanTiens")
                        .HasForeignKey("MaPhieuDatCho")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem.Web.Models.ThanhToan", "ThanhToan")
                        .WithMany("HoanTiens")
                        .HasForeignKey("MaThanhToan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhieuDatCho");

                    b.Navigation("ThanhToan");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.LoTrinh", b =>
                {
                    b.HasOne("FlightBookingSystem.Web.Models.SanBay", "SanBayDen")
                        .WithMany("LoTrinhDen")
                        .HasForeignKey("MaSanBayDen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem.Web.Models.SanBay", "SanBayDi")
                        .WithMany("LoTrinhDi")
                        .HasForeignKey("MaSanBayDi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SanBayDen");

                    b.Navigation("SanBayDi");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.MayBay", b =>
                {
                    b.HasOne("FlightBookingSystem.Web.Models.HangBay", "HangBay")
                        .WithMany("MayBays")
                        .HasForeignKey("MaHangBay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HangBay");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.PhieuDatCho", b =>
                {
                    b.HasOne("FlightBookingSystem.Web.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("PhieuDatChos")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.ThanhToan", b =>
                {
                    b.HasOne("FlightBookingSystem.Web.Models.PhieuDatCho", "PhieuDatCho")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaPhieuDatCho")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhieuDatCho");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.Ve", b =>
                {
                    b.HasOne("FlightBookingSystem.Web.Models.ChangDatCho", "ChangDatCho")
                        .WithMany("Ves")
                        .HasForeignKey("MaChangDatCho")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem.Web.Models.GheChuyenBay", "GheChuyenBay")
                        .WithMany("Ves")
                        .HasForeignKey("MaGheChuyenBay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem.Web.Models.HanhKhach", "HanhKhach")
                        .WithMany("Ves")
                        .HasForeignKey("MaHanhKhach")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem.Web.Models.PhieuDatCho", "PhieuDatCho")
                        .WithMany("Ves")
                        .HasForeignKey("MaPhieuDatCho")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangDatCho");

                    b.Navigation("GheChuyenBay");

                    b.Navigation("HanhKhach");

                    b.Navigation("PhieuDatCho");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.ChangDatCho", b =>
                {
                    b.Navigation("Ves");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.ChuyenBay", b =>
                {
                    b.Navigation("ChangDatChos");

                    b.Navigation("GheChuyenBays");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.DichVuThem", b =>
                {
                    b.Navigation("ChiTietDichVus");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.GheChuyenBay", b =>
                {
                    b.Navigation("Ves");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.GheMayBay", b =>
                {
                    b.Navigation("GheChuyenBays");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.HangBay", b =>
                {
                    b.Navigation("MayBays");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.HangGhe", b =>
                {
                    b.Navigation("GheMayBays");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.HanhKhach", b =>
                {
                    b.Navigation("ChiTietDichVus");

                    b.Navigation("Ves");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.LoTrinh", b =>
                {
                    b.Navigation("ChuyenBays");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.MayBay", b =>
                {
                    b.Navigation("ChuyenBays");

                    b.Navigation("GheMayBays");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.PhieuDatCho", b =>
                {
                    b.Navigation("ChangDatChos");

                    b.Navigation("ChiTietDichVus");

                    b.Navigation("GheDangGius");

                    b.Navigation("HanhKhachs");

                    b.Navigation("HoanTiens");

                    b.Navigation("ThanhToans");

                    b.Navigation("Ves");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.SanBay", b =>
                {
                    b.Navigation("LoTrinhDen");

                    b.Navigation("LoTrinhDi");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.TaiKhoan", b =>
                {
                    b.Navigation("GheDangGius");

                    b.Navigation("PhieuDatChos");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.ThanhToan", b =>
                {
                    b.Navigation("HoanTiens");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.Ve", b =>
                {
                    b.Navigation("ChiTietDichVus");
                });
#pragma warning restore 612, 618
        }
    }
}
