// <auto-generated />
using System;
using FlightBookingSystem.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightBookingSystem.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FlightBookingSystem.Web.Models.ChiTietDichVu", b =>
                {
                    b.Property<int>("MaChiTietDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DichVuThemMaDichVu")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Gia")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaVe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VeMaVe")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaChiTietDichVu");

                    b.HasIndex("DichVuThemMaDichVu");

                    b.HasIndex("VeMaVe");

                    b.HasIndex("MaVe", "MaDichVu")
                        .IsUnique();

                    b.ToTable("ChiTietDichVus");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.ChuyenBay", b =>
                {
                    b.Property<int>("MaChuyenBay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CuaLen")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GiaCoBan")
                        .HasColumnType("TEXT");

                    b.Property<string>("GioBatDauCheckIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("GioHaCanh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GioHaCanhThucTe")
                        .HasColumnType("TEXT");

                    b.Property<string>("GioKetThucCheckIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("GioKhoiHanh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GioKhoiHanhThucTe")
                        .HasColumnType("TEXT");

                    b.Property<string>("GioLenMayBay")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LoTrinhMaLoTrinh")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LyDoTreChuyen")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaLoTrinh")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaMayBay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MayBayMaMayBay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NhaGa")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaChuyenBay");

                    b.HasIndex("LoTrinhMaLoTrinh");

                    b.HasIndex("MayBayMaMayBay");

                    b.HasIndex("MaLoTrinh", "GioKhoiHanh")
                        .HasDatabaseName("IX_ChuyenBay_TimKiem");

                    b.ToTable("ChuyenBays");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.DichVuThem", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Gia")
                        .HasColumnType("TEXT");

                    b.Property<int>("KhoiLuongKg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MoTa")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaDichVu");

                    b.ToTable("DichVuThems");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.GheChuyenBay", b =>
                {
                    b.Property<int>("MaGheChuyenBay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChuyenBayMaChuyenBay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GheMayBayMaGheMayBay")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GiaGhe")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaChuyenBay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaGheMayBay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhienBan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrangThaiGhe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaGheChuyenBay");

                    b.HasIndex("ChuyenBayMaChuyenBay");

                    b.HasIndex("GheMayBayMaGheMayBay");

                    b.HasIndex("MaChuyenBay", "MaGheMayBay")
                        .IsUnique();

                    b.HasIndex("MaChuyenBay", "TrangThaiGhe")
                        .HasDatabaseName("IX_GheChuyenBay_ChuyenBay");

                    b.ToTable("GheChuyenBays");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.GheMayBay", b =>
                {
                    b.Property<int>("MaGheMayBay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DangSuDung")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HangGheMaHangGhe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaHangGhe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaMayBay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MayBayMaMayBay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoGhe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaGheMayBay");

                    b.HasIndex("HangGheMaHangGhe");

                    b.HasIndex("MayBayMaMayBay");

                    b.HasIndex("MaMayBay", "SoGhe")
                        .IsUnique();

                    b.ToTable("GheMayBays");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.HangBay", b =>
                {
                    b.Property<int>("MaHangBay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuocGia")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenHangBay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaHangBay");

                    b.HasIndex("MaCode")
                        .IsUnique();

                    b.ToTable("HangBays");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.HangGhe", b =>
                {
                    b.Property<int>("MaHangGhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HeSoGia")
                        .HasColumnType("TEXT");

                    b.Property<string>("MoTa")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenHangGhe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaHangGhe");

                    b.HasIndex("TenHangGhe")
                        .IsUnique();

                    b.ToTable("HangGhes");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.HanhKhach", b =>
                {
                    b.Property<int>("MaHanhKhach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NgaySinh")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuocTich")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoCCCD")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoHoChieu")
                        .HasColumnType("TEXT");

                    b.HasKey("MaHanhKhach");

                    b.ToTable("HanhKhachs");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.LoTrinh", b =>
                {
                    b.Property<int>("MaLoTrinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GiaCoBan")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KhoangCachKm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaSanBayDen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaSanBayDi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaLoTrinh");

                    b.HasIndex("MaSanBayDen");

                    b.HasIndex("MaSanBayDi", "MaSanBayDen")
                        .IsUnique()
                        .HasDatabaseName("IX_LoTrinh_TimKiem");

                    b.ToTable("LoTrinhs");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.MayBay", b =>
                {
                    b.Property<int>("MaMayBay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DongMayBay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("HangBayMaHangBay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaHangBay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoHieuDangKy")
                        .HasColumnType("TEXT");

                    b.Property<int>("TongSoGhe")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaMayBay");

                    b.HasIndex("HangBayMaHangBay");

                    b.HasIndex("SoHieuDangKy")
                        .IsUnique();

                    b.ToTable("MayBays");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.PhieuDatCho", b =>
                {
                    b.Property<int>("MaPhieuDatCho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NgayDat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TaiKhoanMaTaiKhoan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThoiGianHetHan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaPhieuDatCho");

                    b.HasIndex("MaTaiKhoan")
                        .HasDatabaseName("IX_PhieuDatCho_TaiKhoan");

                    b.HasIndex("TaiKhoanMaTaiKhoan");

                    b.ToTable("PhieuDatChos");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.SanBay", b =>
                {
                    b.Property<string>("MaSanBay")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuocGia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSanBay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThanhPho")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaSanBay");

                    b.ToTable("SanBays");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NgayTao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SoDienThoai")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LyDoLoi")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaGiaoDich")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaPhieuDatCho")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NgayThanhToan")
                        .HasColumnType("TEXT");

                    b.Property<string>("NhaCungCap")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhieuDatChoMaPhieuDatCho")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaPhieuDatCho")
                        .HasDatabaseName("IX_ThanhToan_PhieuDatCho");

                    b.HasIndex("PhieuDatChoMaPhieuDatCho");

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.Ve", b =>
                {
                    b.Property<int>("MaVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GheChuyenBayMaGheChuyenBay")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GiaVe")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HanhKhachMaHanhKhach")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaGheChuyenBay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaHanhKhach")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaPhieuDatCho")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PhieuDatChoMaPhieuDatCho")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrangThaiVe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaVe");

                    b.HasIndex("GheChuyenBayMaGheChuyenBay");

                    b.HasIndex("HanhKhachMaHanhKhach");

                    b.HasIndex("MaGheChuyenBay")
                        .IsUnique()
                        .HasDatabaseName("UQ_Ve_GheChuyenBay_ConHieuLuc")
                        .HasFilter("TrangThaiVe NOT IN ('Canceled', 'Refunded')");

                    b.HasIndex("MaPhieuDatCho")
                        .HasDatabaseName("IX_Ve_PhieuDatCho");

                    b.HasIndex("PhieuDatChoMaPhieuDatCho");

                    b.ToTable("Ves");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.ChiTietDichVu", b =>
                {
                    b.HasOne("FlightBookingSystem.Web.Models.DichVuThem", "DichVuThem")
                        .WithMany()
                        .HasForeignKey("DichVuThemMaDichVu");

                    b.HasOne("FlightBookingSystem.Web.Models.Ve", "Ve")
                        .WithMany()
                        .HasForeignKey("VeMaVe");

                    b.Navigation("DichVuThem");

                    b.Navigation("Ve");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.ChuyenBay", b =>
                {
                    b.HasOne("FlightBookingSystem.Web.Models.LoTrinh", "LoTrinh")
                        .WithMany()
                        .HasForeignKey("LoTrinhMaLoTrinh");

                    b.HasOne("FlightBookingSystem.Web.Models.MayBay", "MayBay")
                        .WithMany()
                        .HasForeignKey("MayBayMaMayBay");

                    b.Navigation("LoTrinh");

                    b.Navigation("MayBay");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.GheChuyenBay", b =>
                {
                    b.HasOne("FlightBookingSystem.Web.Models.ChuyenBay", "ChuyenBay")
                        .WithMany()
                        .HasForeignKey("ChuyenBayMaChuyenBay");

                    b.HasOne("FlightBookingSystem.Web.Models.GheMayBay", "GheMayBay")
                        .WithMany()
                        .HasForeignKey("GheMayBayMaGheMayBay");

                    b.Navigation("ChuyenBay");

                    b.Navigation("GheMayBay");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.GheMayBay", b =>
                {
                    b.HasOne("FlightBookingSystem.Web.Models.HangGhe", "HangGhe")
                        .WithMany()
                        .HasForeignKey("HangGheMaHangGhe");

                    b.HasOne("FlightBookingSystem.Web.Models.MayBay", "MayBay")
                        .WithMany()
                        .HasForeignKey("MayBayMaMayBay");

                    b.Navigation("HangGhe");

                    b.Navigation("MayBay");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.LoTrinh", b =>
                {
                    b.HasOne("FlightBookingSystem.Web.Models.SanBay", "SanBayDen")
                        .WithMany()
                        .HasForeignKey("MaSanBayDen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem.Web.Models.SanBay", "SanBayDi")
                        .WithMany()
                        .HasForeignKey("MaSanBayDi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SanBayDen");

                    b.Navigation("SanBayDi");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.MayBay", b =>
                {
                    b.HasOne("FlightBookingSystem.Web.Models.HangBay", "HangBay")
                        .WithMany()
                        .HasForeignKey("HangBayMaHangBay");

                    b.Navigation("HangBay");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.PhieuDatCho", b =>
                {
                    b.HasOne("FlightBookingSystem.Web.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanMaTaiKhoan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.ThanhToan", b =>
                {
                    b.HasOne("FlightBookingSystem.Web.Models.PhieuDatCho", "PhieuDatCho")
                        .WithMany()
                        .HasForeignKey("PhieuDatChoMaPhieuDatCho");

                    b.Navigation("PhieuDatCho");
                });

            modelBuilder.Entity("FlightBookingSystem.Web.Models.Ve", b =>
                {
                    b.HasOne("FlightBookingSystem.Web.Models.GheChuyenBay", "GheChuyenBay")
                        .WithMany()
                        .HasForeignKey("GheChuyenBayMaGheChuyenBay");

                    b.HasOne("FlightBookingSystem.Web.Models.HanhKhach", "HanhKhach")
                        .WithMany()
                        .HasForeignKey("HanhKhachMaHanhKhach");

                    b.HasOne("FlightBookingSystem.Web.Models.PhieuDatCho", "PhieuDatCho")
                        .WithMany()
                        .HasForeignKey("PhieuDatChoMaPhieuDatCho");

                    b.Navigation("GheChuyenBay");

                    b.Navigation("HanhKhach");

                    b.Navigation("PhieuDatCho");
                });
#pragma warning restore 612, 618
        }
    }
}
